// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl22j7alXMUMZhGPXsQvvM62uUZml8Lsg',
    appId: '1:239669970593:web:f7f57edd9b654d954b92e0',
    messagingSenderId: '239669970593',
    projectId: 'straynest-4fbc6',
    authDomain: 'straynest-4fbc6.firebaseapp.com',
    storageBucket: 'straynest-4fbc6.firebasestorage.app',
    measurementId: 'G-T5BWT10B73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUr1mwUxfdZcCEPELG3wmo-QXJLW0j_Lg',
    appId: '1:239669970593:android:befd18ce711e1ee94b92e0',
    messagingSenderId: '239669970593',
    projectId: 'straynest-4fbc6',
    storageBucket: 'straynest-4fbc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9UVNJwLzXlz7JmpBE-YZhBY5zbXtUQYQ',
    appId: '1:239669970593:ios:d51adf8499e37fc64b92e0',
    messagingSenderId: '239669970593',
    projectId: 'straynest-4fbc6',
    storageBucket: 'straynest-4fbc6.firebasestorage.app',
    iosClientId: '239669970593-tk8ukmebbssg3rs8g8cbr3kqg41r55sf.apps.googleusercontent.com',
    iosBundleId: 'com.example.strayNest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9UVNJwLzXlz7JmpBE-YZhBY5zbXtUQYQ',
    appId: '1:239669970593:ios:d51adf8499e37fc64b92e0',
    messagingSenderId: '239669970593',
    projectId: 'straynest-4fbc6',
    storageBucket: 'straynest-4fbc6.firebasestorage.app',
    iosClientId: '239669970593-tk8ukmebbssg3rs8g8cbr3kqg41r55sf.apps.googleusercontent.com',
    iosBundleId: 'com.example.strayNest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl22j7alXMUMZhGPXsQvvM62uUZml8Lsg',
    appId: '1:239669970593:web:c4ebeddf3f5e90224b92e0',
    messagingSenderId: '239669970593',
    projectId: 'straynest-4fbc6',
    authDomain: 'straynest-4fbc6.firebaseapp.com',
    storageBucket: 'straynest-4fbc6.firebasestorage.app',
    measurementId: 'G-7TZECJHBM4',
  );
}
